"""2026-07-02 当日可申购港股 IPO 的本地结构化数据。"""


def _item(name, english_name, code, industry, price_low, price_high, deadline, metrics, risks):
    return {"name": name, "english_name": english_name, "code": f"{code}.HK", "industry": industry,
            "price_low": price_low, "price_high": price_high, "deadline": deadline,
            "metrics": metrics, "risks": risks, "is_sample": False}


SAMPLE_IPOS = [
    _item("同仁堂医养", "Beijing Tong Ren Tang Healthcare Investment Co., Ltd.", "02667", "中医医疗服务", 5.48, 6.21, "2026-07-02",
          {"has_cornerstone": True, "cornerstone_quality_good": None, "greenshoe": False, "is_ah": False,
           "peer_valuation_discount": None, "sponsor_quality_good": True, "subscription_multiple": 127.08,
           "minimum_subscription_amount": 3136.31, "issuance_shares": 108153500, "lot_size": 500,
           "cornerstone_investors": [], "cornerstone_ratio": 46.79,
           "sponsors": ["中金公司", "工银国际", "广发证券", "农银国际"],
           "company_quality": ["重启招股后价格区间较首次下调约25%。", "三家基石合计认购约2.96亿港元。", "2025年净利率约4%，盈利安全垫有限。"]},
          ["曾因招股情况不理想延迟上市。", "医疗服务扩张、运营效率及合规风险仍需跟踪。"]),
    _item("东方科脉", "DKE Holding Company Limited", "01770", "电子纸显示模组", 78.64, 101.11, "2026-07-03",
          {"has_cornerstone": None, "cornerstone_quality_good": None, "greenshoe": False, "is_ah": False,
           "peer_valuation_discount": -102, "sponsor_quality_good": True, "subscription_multiple": 63.45,
           "minimum_subscription_amount": 5106.50, "issuance_shares": 5118600, "lot_size": 50,
           "cornerstone_investors": [], "cornerstone_ratio": None, "sponsors": ["中信证券"],
           "company_quality": ["2025年收入约17.13亿元，同比增长约48.75%。", "2025年净利润约0.80亿元，同比增长约50.23%。", "2025年毛利率约16.36%。"]},
          ["发行PE约44至57倍，高于表内可比区间。", "显示模组行业竞争及产品周期可能压缩利润率。"]),
    _item("瑞为技术", "Reconova Technologies Co., Ltd.", "07656", "企业级视觉AI", 21.66, 21.66, "2026-07-03",
          {"has_cornerstone": None, "cornerstone_quality_good": None, "greenshoe": False, "is_ah": False,
           "peer_valuation_discount": -1, "sponsor_quality_good": True, "subscription_multiple": 384.64,
           "minimum_subscription_amount": 4375.69, "issuance_shares": 28087000, "lot_size": 200,
           "cornerstone_investors": [], "cornerstone_ratio": None, "sponsors": ["华泰国际", "建银国际", "农银国际"],
           "company_quality": ["2025年收入约4.43亿元。", "2025年毛利率约37.72%。", "民航企业视觉智能产品市场份额约8.7%。"]},
          ["2025年净亏损约0.68亿元。", "前五大客户收入占比约60.3%。"]),
    _item("易控智驾", "EACON Group Co., Ltd.", "07687", "矿区无人驾驶", 81.16, 87.92, "2026-07-03",
          {"has_cornerstone": None, "cornerstone_quality_good": None, "greenshoe": False, "is_ah": False,
           "peer_valuation_discount": 6, "sponsor_quality_good": True, "subscription_multiple": 26.44,
           "minimum_subscription_amount": 4440.34, "issuance_shares": 26132000, "lot_size": 50,
           "cornerstone_investors": [], "cornerstone_ratio": None, "sponsors": ["国泰海通", "麦格理", "中信证券"],
           "company_quality": ["2025年收入约14.35亿元，同比增长约45.53%。", "矿区无人驾驶具备明确行业场景。", "发行PS约7.3至7.9倍。"]},
          ["2025年净亏损约5.16亿元。", "毛利率约10.13%，商业化与现金消耗压力较高。"]),
    _item("宝盖新材", "Shandong Baogai New Materials Technology Co., Ltd.", "08090", "工业制造", 6.15, 8.51, "2026-07-03",
          {"has_cornerstone": None, "cornerstone_quality_good": None, "greenshoe": False, "is_ah": False,
           "peer_valuation_discount": -10, "sponsor_quality_good": False, "subscription_multiple": 205.59,
           "minimum_subscription_amount": 4297.91, "issuance_shares": 14470000, "lot_size": 500,
           "cornerstone_investors": [], "cornerstone_ratio": None, "sponsors": ["中泰国际"],
           "company_quality": ["2025年收入约1.44亿元。", "2025年净利润约0.24亿元。", "发行后市值约3.56至4.92亿港元。"]},
          ["公司及发行规模较小。", "同业估值证据和上市后流动性存在不确定性。"]),
    _item("基本半导体", "BASiC Semiconductor Co., Ltd.", "09971", "碳化硅功率半导体", 27.49, 31.62, "2026-07-03",
          {"has_cornerstone": None, "cornerstone_quality_good": None, "greenshoe": False, "is_ah": False,
           "peer_valuation_discount": None, "sponsor_quality_good": True, "subscription_multiple": 983.55,
           "minimum_subscription_amount": 6387.78, "issuance_shares": 27386200, "lot_size": 200,
           "cornerstone_investors": [], "cornerstone_ratio": None, "sponsors": ["国金证券（香港）", "中银国际"],
           "company_quality": ["聚焦碳化硅功率半导体，具备国产替代逻辑。", "2025年下半年综合毛利率转正。", "本批实时认购倍数最高。"]},
          ["全年盈利能力尚未稳定。", "资本开支、技术迭代及高热度定价风险较高。"]),
    _item("MOMENTA-W", "Momenta Global Limited", "06880", "自动驾驶软件", 295.60, 295.60, "2026-07-03",
          {"has_cornerstone": True, "cornerstone_quality_good": True, "greenshoe": True, "is_ah": False,
           "peer_valuation_discount": -517, "sponsor_quality_good": True, "subscription_multiple": 47.77,
           "minimum_subscription_amount": 5971.62, "issuance_shares": 19938300, "lot_size": 20,
           "cornerstone_investors": ["GIC", "富达", "贝莱德", "橡树资本", "富兰克林邓普顿"], "cornerstone_ratio": 50.0,
           "sponsors": ["中金公司", "德意志银行"],
           "company_quality": ["2025年收入约24.13亿元。", "2025年毛利率约71.58%。", "量产车解决方案形成数据闭环。"]},
          ["仍录得较大净亏损。", "发行PS约50倍，显著高于可比公司。", "前五大客户收入占比约62.6%。"]),
    _item("齐云山食品", "Jiangxi Qiyunshan Food Co., Ltd.", "02797", "食品饮料", 5.00, 8.00, "2026-07-06",
          {"has_cornerstone": None, "cornerstone_quality_good": None, "greenshoe": False, "is_ah": False,
           "peer_valuation_discount": 20, "sponsor_quality_good": False, "subscription_multiple": 6.48,
           "minimum_subscription_amount": 4040.34, "issuance_shares": 25000000, "lot_size": 500,
           "cornerstone_investors": [], "cornerstone_ratio": None, "sponsors": ["中泰国际"],
           "company_quality": ["2025年收入约3.14亿元。", "2025年净利润约0.49亿元。", "2025年毛利率约51.32%。"]},
          ["公司规模较小。", "同业估值证据有限且上市后流动性可能不足。"]),
    _item("珞石机器人", "ROKAE (Shandong) Robotics Group Inc.", "03752", "工业及协作机器人", 38.00, 38.00, "2026-07-06",
          {"has_cornerstone": True, "cornerstone_quality_good": True, "greenshoe": False, "is_ah": False,
           "peer_valuation_discount": -99, "sponsor_quality_good": True, "subscription_multiple": 7.75,
           "minimum_subscription_amount": 3838.32, "issuance_shares": 23031900, "lot_size": 100,
           "cornerstone_investors": ["广发基金", "华泰资本"], "cornerstone_ratio": None,
           "sponsors": ["中金公司", "国泰海通"],
           "company_quality": ["2025年收入约5.22亿元。", "2025年毛利率约21.89%。", "海外收入占比约8.9%。"]},
          ["2025年净亏损约1.79亿元。", "发行PS约17.5倍，高于多数可比口径。"]),
    _item("普源精电", "RIGOL Technologies Co., Ltd.", "00537", "电子测量仪器", 45.98, 45.98, "2026-07-06",
          {"has_cornerstone": True, "cornerstone_quality_good": None, "greenshoe": False, "is_ah": True,
           "ah_premium": None, "sponsor_quality_good": True, "subscription_multiple": 7.25,
           "minimum_subscription_amount": 4644.37, "issuance_shares": 24802200, "lot_size": 100,
           "cornerstone_investors": [], "cornerstone_ratio": None, "sponsors": ["中信证券"],
           "company_quality": ["2025年收入约9.00亿元。", "2025年净利润约0.86亿元。", "2025年毛利率约52.84%。"]},
          ["认购热度处于中下游。", "缺少同日A/H折溢价数据。"]),
    _item("立讯精密", "Luxshare Precision Industry Co., Ltd.", "02475", "消费电子制造", 63.28, 63.28, "2026-07-06",
          {"has_cornerstone": None, "cornerstone_quality_good": None, "greenshoe": False, "is_ah": True,
           "ah_premium": None, "sponsor_quality_good": True, "subscription_multiple": 0.90,
           "minimum_subscription_amount": 6391.82, "issuance_shares": 383472800, "lot_size": 100,
           "cornerstone_investors": [], "cornerstone_ratio": None,
           "sponsors": ["中信证券", "高盛", "中金公司", "汇丰"],
           "company_quality": ["2025年收入约3323.44亿元。", "2025年净利润约181.70亿元。", "同批公司中业务规模和成熟度领先。"]},
          ["公开认购尚未足额。", "大体量融资承接、客户集中和全球供应链风险。"]),
    _item("三环集团", "Chaozhou Three-Circle (Group) Co., Ltd.", "06951", "电子陶瓷", 100.30, 100.30, "2026-07-06",
          {"has_cornerstone": True, "cornerstone_quality_good": True, "greenshoe": False, "is_ah": True,
           "ah_premium": None, "sponsor_quality_good": True, "subscription_multiple": 12.62,
           "minimum_subscription_amount": 10131.15, "issuance_shares": 71364300, "lot_size": 100,
           "cornerstone_investors": ["淡马锡", "摩根大通", "阿里巴巴关联主体", "腾讯关联主体", "高盛资产", "宏利", "泰康人寿"],
           "cornerstone_ratio": None, "sponsors": ["中国银河国际"],
           "company_quality": ["电子陶瓷细分行业龙头。", "引入17家基石投资者。", "基石阵容包含主权、长线及产业资本。"]},
          ["发行后市值和融资规模较大。", "缺少同日A/H折溢价数据。"]),
    _item("鼎泰高科", "Guangdong Dtech Technology Co., Ltd.", "01377", "刀具及功能性材料", 380.00, 380.00, "2026-07-06",
          {"has_cornerstone": True, "cornerstone_quality_good": None, "greenshoe": False, "is_ah": True,
           "ah_premium": None, "sponsor_quality_good": True, "subscription_multiple": 10.37,
           "minimum_subscription_amount": 38383.24, "issuance_shares": 12632000, "lot_size": 100,
           "cornerstone_investors": [], "cornerstone_ratio": None, "sponsors": ["中信证券", "汇丰"],
           "company_quality": ["2025年收入约20.84亿元，同比增长34.2%。", "2025年净利润约4.32亿元。", "2025年PCB钻针全球市场份额约29.2%。"]},
          ["最高发行价较高。", "缺少同日A/H折溢价数据且受PCB周期影响。"]),
    _item("晶合集成", "Nexchip Semiconductor (China) Limited", "02249", "晶圆代工", 30.00, 32.30, "2026-07-07",
          {"has_cornerstone": None, "cornerstone_quality_good": None, "greenshoe": False, "is_ah": True,
           "ah_premium": None, "sponsor_quality_good": True, "subscription_multiple": 1.33,
           "minimum_subscription_amount": 3262.57, "issuance_shares": 216167000, "lot_size": 100,
           "cornerstone_investors": [], "cornerstone_ratio": None, "sponsors": ["中金公司", "中信证券"],
           "company_quality": ["晶圆代工具备产业战略价值。", "重资产模式应结合PB和PS观察。", "发行后市值约667.13至718.27亿港元。"]},
          ["认购倍数较低。", "晶圆代工周期性强，缺少统一PB/PS和A/H比价。"]),
    _item("滨化股份", "Befar Group Co., Ltd.", "06745", "基础化工", 3.59, 3.59, "2026-07-07",
          {"has_cornerstone": None, "cornerstone_quality_good": None, "greenshoe": False, "is_ah": True,
           "ah_premium": None, "sponsor_quality_good": True, "subscription_multiple": 1.99,
           "minimum_subscription_amount": 3626.21, "issuance_shares": 352126000, "lot_size": 1000,
           "cornerstone_investors": [], "cornerstone_ratio": None, "sponsors": ["华泰国际", "建银国际"],
           "company_quality": ["2025年收入约148.36亿元。", "2025年净利润约2.35亿元。", "发行价格较低、业务规模成熟。"]},
          ["基础化工周期性明显。", "毛利率约9.81%、认购热度较低且缺少A/H比价。"]),
    _item("永康控股", "EKH Limited", "02523", "货运物流", 2.20, 2.68, "2026-07-08",
          {"has_cornerstone": None, "cornerstone_quality_good": None, "greenshoe": False, "is_ah": False,
           "peer_valuation_discount": -15, "sponsor_quality_good": False, "subscription_multiple": 4.47,
           "minimum_subscription_amount": 5414.05, "issuance_shares": 51600000, "lot_size": 2000,
           "cornerstone_investors": [], "cornerstone_ratio": None,
           "sponsors": ["富强企业融资", "华富建业企业融资"],
           "company_quality": ["新加坡集装箱堆场运营商。", "2025年收入约1.49亿新加坡元。", "2025年净利润约0.13亿新加坡元。"]},
          ["成长性与业务稀缺性有限。", "小市值发行存在流动性风险。"]),
]
