SAMPLE_IPOS = [
    {
        "name": "示例科技有限公司", "english_name": "SampleTech Ltd.", "code": "06999.HK",
        "industry": "资讯科技", "price_low": 15.0, "price_high": 18.0, "deadline": "2026-07-08",
        "metrics": {"has_cornerstone": True, "cornerstone_quality_good": True, "greenshoe": True,
                    "is_ah": False, "peer_valuation_discount": 25, "sponsor_quality_good": True,
                    "revenue_growth": 43, "profit_growth": 52, "net_margin": 22, "debt_ratio": 35,
                    "cornerstone_ratio": 38, "subscription_multiple": 82, "public_float_ratio": 28,
                    "dilution_ratio": 12, "industry_outlook": 88, "pe_discount": 25, "ps_discount": 18,
                    "pricing_attractiveness": 84, "news_sentiment": 0.7, "subscription_momentum": 91},
        "risks": ["样例公司规模仍较小，盈利持续性尚待验证。", "科技行业竞争激烈，估值可能出现较大波动。"],
    },
    {
        "name": "示例生物医药有限公司", "english_name": "Sample BioPharma Ltd.", "code": "02555.HK",
        "industry": "医疗保健", "price_low": 20.0, "price_high": 24.0, "deadline": "2026-07-09",
        "metrics": {"has_cornerstone": True, "cornerstone_quality_good": False, "greenshoe": True,
                    "is_ah": False, "peer_valuation_discount": 8, "sponsor_quality_good": True,
                    "revenue_growth": 28, "profit_growth": 12, "net_margin": 8, "debt_ratio": 48,
                    "cornerstone_ratio": 30, "subscription_multiple": 36, "public_float_ratio": 25,
                    "dilution_ratio": 18, "industry_outlook": 72, "pe_discount": 8, "ps_discount": 5,
                    "pricing_attractiveness": 63, "news_sentiment": 0.3, "subscription_momentum": 64},
        "risks": ["研发投入较高，产品商业化进度存在不确定性。", "监管审批可能影响上市后业绩节奏。"],
    },
    {
        "name": "示例消费集团有限公司", "english_name": "Sample Consumer Group Ltd.", "code": "03333.HK",
        "industry": "非必需性消费", "price_low": 8.5, "price_high": 10.5, "deadline": "2026-07-07",
        "metrics": {"has_cornerstone": False, "cornerstone_quality_good": False, "greenshoe": False,
                    "is_ah": False, "peer_valuation_discount": -18, "sponsor_quality_good": False,
                    "revenue_growth": 5, "profit_growth": -12, "net_margin": 3, "debt_ratio": 78,
                    "cornerstone_ratio": 5, "subscription_multiple": 3, "public_float_ratio": 16,
                    "dilution_ratio": 30, "industry_outlook": 42, "pe_discount": -18, "ps_discount": -12,
                    "pricing_attractiveness": 35, "news_sentiment": -0.5, "subscription_momentum": 22},
        "risks": ["收入增长放缓且利润承压。", "负债率较高，消费复苏不及预期可能放大风险。"],
    },
    {
        "name": "示例新能源有限公司", "english_name": "Sample New Energy Ltd.", "code": "03888.HK",
        "industry": "工业", "price_low": 12.0, "price_high": 14.0, "deadline": "2026-07-10",
        "metrics": {"has_cornerstone": True, "cornerstone_quality_good": False, "greenshoe": True,
                    "is_ah": True, "ah_premium": 55, "sponsor_quality_good": False,
                    "revenue_growth": 22, "profit_growth": 18, "net_margin": 11, "debt_ratio": 57,
                    "cornerstone_ratio": 21, "subscription_multiple": 22, "public_float_ratio": 24,
                    "dilution_ratio": 21, "industry_outlook": 68, "pe_discount": 3, "ps_discount": 0,
                    "pricing_attractiveness": 58, "news_sentiment": 0.1, "subscription_momentum": 55},
        "risks": ["原材料价格变化可能侵蚀利润。", "行业补贴及政策变化可能影响需求。"],
    },
]
